---
- hosts: haipproxy
  remote_user: zzw
  vars:
    splash_url: http://127.0.0.1:8050
    redis_host: 127.0.0.1
    redis_port: 6379
    redis_password: ''
    haipproxy_path: "/home/zzw/haipproxy"
    software_path: "/home/zzw/software"
  tasks:
    - name: create software dir
      file:
        path: "{{ software_path }}"
        state: directory
        group: zzw
        owner: zzw
    - name: prepare environment in CentOS
      yum:
        name: "{{ item }}"
      register: yum_res
      retries: 5
      until: yum_res | success
      with_items:
        - bzip2
        - openssl-devel
        - unzip.x86_64
        - sqlite-devel
        - git
      become: True
      when: ansible_os_family == "RedHat"
    - name: prepare environment in Ubuntu
      apt:
        name: "{{ item }}"
      register: apt_res
      retries: 5
      until: apt_res | success
      with_items:
        - bzip2
        - openssl
        - libssl-dev
        - zip
        - unzip
        - libsqlite3-dev
        - git
      become: True
      when: ansible_os_family == "Debian"
    - include: python3.yml
    - name: remove old code
      file:
        path: "{{ haipproxy_path }}"
        state: absent
    - name: get haipproxy source code
      git:
        repo: "https://github.com/SpiderClub/haipproxy.git"
        dest: "{{ haipproxy_path }}"
      register: haipproxy_code_res
      retries: 5
      until: haipproxy_code_res | success
    - include: redis.yml
    - name: haipproxy setting
      template:
        src: haipproxy/settings.py
        dest: "{{ haipproxy_path }}/haipproxy/config/settings.py"
    - include: splash.yml
    - name: unarchive Twisted
      unarchive:
        src: https://files.pythonhosted.org/packages/a2/37/298f9547606c45d75aa9792369302cc63aa4bbcf7b5f607560180dd099d2/Twisted-17.9.0.tar.bz2
        dest: "{{ software_path }}"
        remote_src: yes
      register: twisted_res
      retries: 5
      until: twisted_res | success
    - name: install Twisted
      shell: python3.6.7 setup.py install
      args:
        chdir: "{{ software_path }}/Twisted-17.9.0"
      register: install_twisted_res
      retries: 5
      until: install_twisted_res | success
      become: True
    - name: pip requirements
      pip:
        requirements: "{{ haipproxy_path }}/requirements.txt"
        executable: pip3.6.7
      register: pip_res
      retries: 5
      until: pip_res | success
      become: True
    - name: start haipproxy crawler crawler common
      shell: nohup python3.6.7 crawler_booter.py --usage crawler common > crawler.log 2>&1 &
      args:
        chdir: "{{ haipproxy_path }}"
        executable: /bin/bash
    - name: start haipproxy scheduler crawler common
      shell: nohup python3.6.7 scheduler_booter.py --usage crawler common > crawler_scheduler.log 2>&1 &
      args:
        chdir: "{{ haipproxy_path }}"
        executable: /bin/bash
    - name: start haipproxy crawler validator init
      shell: nohup python3.6.7 crawler_booter.py --usage validator init > init_validator.log 2>&1 &
      args:
        chdir: "{{ haipproxy_path }}"
        executable: /bin/bash
    - name: start haipproxy crawler validator https
      shell: nohup python3.6.7 crawler_booter.py --usage validator https > https_validator.log 2>&1&
      args:
        chdir: "{{ haipproxy_path }}"
        executable: /bin/bash
    - name: start haipproxy scheduler validator https
      shell: nohup python3.6.7 scheduler_booter.py --usage validator https > validator_scheduler.log 2>&1 &
      args:
        chdir: "{{ haipproxy_path }}"
        executable: /bin/bash

